name: Deploy Zensical Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Deploy Site
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
        run: |
          $HOME/.local/bin/uvx --with ghp-import zensical build
          $HOME/.local/bin/uvx ghp-import -n -p -f site
